// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu7j0FVrM9yhSsmaCLFB0fdgokPh4m0UU',
    appId: '1:179837147792:web:9fdc43d2bdd24e51351615',
    messagingSenderId: '179837147792',
    projectId: 'flutterlearn-844ed',
    authDomain: 'flutterlearn-844ed.firebaseapp.com',
    storageBucket: 'flutterlearn-844ed.firebasestorage.app',
    measurementId: 'G-H8JMYGC2MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHh2W-dgTrK3MaPtgkmbeBvrxt2FX40GU',
    appId: '1:179837147792:android:e954c10bd66b56a4351615',
    messagingSenderId: '179837147792',
    projectId: 'flutterlearn-844ed',
    storageBucket: 'flutterlearn-844ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1eMBUSEQGUoxsfjQ5DZT9i4qYK61Bhg',
    appId: '1:179837147792:ios:e63ec0a973b6d46e351615',
    messagingSenderId: '179837147792',
    projectId: 'flutterlearn-844ed',
    storageBucket: 'flutterlearn-844ed.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu1eMBUSEQGUoxsfjQ5DZT9i4qYK61Bhg',
    appId: '1:179837147792:ios:e63ec0a973b6d46e351615',
    messagingSenderId: '179837147792',
    projectId: 'flutterlearn-844ed',
    storageBucket: 'flutterlearn-844ed.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu7j0FVrM9yhSsmaCLFB0fdgokPh4m0UU',
    appId: '1:179837147792:web:a9ba96733f51ea47351615',
    messagingSenderId: '179837147792',
    projectId: 'flutterlearn-844ed',
    authDomain: 'flutterlearn-844ed.firebaseapp.com',
    storageBucket: 'flutterlearn-844ed.firebasestorage.app',
    measurementId: 'G-M9SZ948R88',
  );
}
